vaadin.launch-browser=true
spring.application.name=world-cup

spring.ai.openai.api-key=${GROQ_API_KEY}
spring.ai.openai.base-url=https://api.groq.com/openai/v1

spring.datasource.url=jdbc:postgresql://localhost:5432/copa2026
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

spring.ai.vectorstore.pgvector.initialize-schema=true
